- title: Pacific Coastlines Change
  description:
    Coastline Change across 30 years for every Pacific island country and territory – with ongoing monitoring of erosion (land loss) and deposition (where areas increase) 
  thumbnailUrl: ./images/apps/coastlines.png
  links:
    - title: Explore
      url: https://www.digitalearthpacific.org
    - title: Learn
      url: https://www.digitalearthpacific.org

- title: Pacific Mangroves Change Detection
  description:
    Pacific Mangroves Change Detection across 20 years.
  thumbnailUrl: ./images/apps/mangroves.png
  links:
    - title: Explore Land Classification
      url: https://www.digitalearthpacific.org
    - title: Learn
      url: https://www.digitalearthpacific.org

- title: Land Cover Change Detection
  description:
    Land Cover Change Analysis over 30 years
  thumbnailUrl: ./images/apps/landcover.png
  links:
    - title: Explore
      url: https://www.digitalearthpacific.org
    - title: Learn
      url: https://www.digitalearthpacific.org

- title: Vegetation Early Disease Detection (SIPI)
  description:
    Structure Insensitive Pigment Index (SIPI) which is helpful in early disease detection in vegetation.
  thumbnailUrl: ./images/apps/carbonplan-wide-fs8.jpg
  links:
    - title: Explore
      url: https://www.digitalearthpacific.org
    - title: Learn
      url: https://www.digitalearthpacific.org

