- title: The Pacific further invests in data and decision-ready tools to support Coastal and Marine Spatial Planning
  description: This initiative, valued at USD 3.04 million, funded through the Republic of Korea (ROK) – Pacific Islands Forum (PIF) Cooperation Fund, is allocated to SPC, KIOST, and the Pacific Islands Forum Secretariat (PIFS) for the implementation of the Development of Decision Ready Tools to Support Coastal and Marine Spatial Planning (II) project. 
  url: https://spc.int/updates/news/joint-release/2025/10/the-pacific-further-invests-in-data-and-decision-ready-tools-to
  source: Pacific Community (SPC)
  published: 28 October, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-10/IMG_7624.JPG.webp?itok=OafKxO_V
  
- title: Fiji Concludes the Management and Conservation of Blue Carbon Ecosystems (MACBLUE) Project with closing event
  description: The MACBLUE project partners, the Ministry of Environment and Climate Change, Secretariat of the Pacific Regional Environment Programme (SPREP), the Pacific Community (SPC), and the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ), gathered on the 23rd of October in Suva to mark the successful closing of the project in Fiji. 
  url: https://spc.int/updates/news/joint-release/2025/10/fiji-concludes-the-management-and-conservation-of-blue-carbon
  source: Pacific Community (SPC)
  published: 27 October, 2025
  banner: https://spc.int/sites/default/files/styles/gallery_thumbnail/public/2025-10/2S4A7890.JPG?itok=KHH3_Eno
  
- title: Fighting invasive species to protect Vanuatu’s forests and people
  description: Invasive species are the leading driver of biodiversity loss in the Pacific, undermining food security, freshwater systems, and climate resilience. For Vanuatu, where forests cover more than one-third of the land and provide vital resources for communities, tackling invasive plants has become a national priority. 
  url: https://www.spc.int/updates/blog/dynamic-story/2025/09/fighting-invasive-species-to-protect-vanuatus-forests-and-people
  source: Pacific Community (SPC)
  published: 25 September, 2025
  banner: https://spc-cps.shorthandstories.com/Fighting-invasive-species-to-protect-Vanuatus-forests-and-people/assets/ZpvDKcPwRe/img_4954-2438x3251.jpg
  
- title: The Pacific Community and the Pacific GIS and Remote Sensing Council sign an MoU to strengthen Pacific geospatial work 
  description: The Pacific Community (SPC) and the Pacific GIS and Remote Sensing Council (PGRSC) have signed a Memorandum of Understanding (MoU) to collaborate on outreach, training, and promotion of regional networking in support of strengthening geospatial and earth observation work for Pacific communities, thereby better informing decision-makers and the public about the importance and great potential of these technologies. 
  url: https://www.spc.int/updates/news/joint-release/2025/09/the-pacific-community-and-the-pacific-gis-and-remote-sensing
  source: Pacific Community (SPC)
  published: 18 September, 2025
  banner: https://www.spc.int/sites/default/files/styles/max_1300x1300/public/2025-09/grfdgfdd.png.webp?itok=c2ulm_uI
  
- title: SPC Director General's remarks during the MOU signing between the Pacific GIS and Remote Sensing Council (PGRSC) and SPC 
  description: The signing of this Memorandum of Understanding between the Pacific Community and the Pacific GIS and Remote Sensing Council is more than a partnership on paper. 
  url: https://www.spc.int/updates/blog/director-general/2025/09/spc-director-generals-remarks-during-the-mou-signing-between
  source: Pacific Community (SPC)
  published: 17 September, 2025
  banner: https://www.spc.int/sites/default/files/styles/max_1300x1300/public/2025-09/RS1497_Dr%20Stuart%20Michin%20-%20SPC%20Director-General%20%281%29%201.jpg.webp?itok=90lzfYpc

- title: Vanuatu’s preparedness for disaster and climate change - An experiment in data science
  description: One of the world’s most disaster-prone nations, the Republic of Vanuatu has executed an innovative experiment that seeks to improve its climate resilience through data science, supported by the Pacific Community (SPC) and World Bank.
  url: https://www.spc.int/updates/blog/2025/07/vanuatus-preparedness-for-disaster-and-climate-change-an-experiment-in-data
  source: Pacific Community (SPC)
  published: 30 July, 2025
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2025-07/RS2328_Desurmont-Torba%20Province-2014-201504160936%20%285%29.JPG?itok=RWIZfZLh
  
- title: Mapping for the future - MACBLUE led workshop upskills Vanuatu in seagrass and mangrove conservation 
  description: The MACBLUE GIS workshop series concluded last week in Vanuatu, bringing together key stakeholders for a week-long event from June 23 to 27.
  url: https://www.spc.int/updates/news/joint-release/2025/07/mapping-for-the-future-macblue-led-workshop-upskills-vanuatu-in
  source: Pacific Community (SPC)
  published: 9 July, 2025
  banner: https://www.spc.int/sites/default/files/styles/max_1300x1300/public/2025-07/Tima%20Allason_Pic%201.JPG.webp?itok=TgiorWHg
    
- title: Identifying forest invasive species in Fiji and Tonga using machine learning - A Pacific Islands case study
  description: Forest and land cover across the Pacific are undergoing rapid transformation. In many areas, the removal of native vegetation and deforestation, whether through agriculture, urban development, or natural disasters such as cyclones, have made ecosystems increasingly vulnerable to invasion by non-native plant species. 
  url: https://www.spc.int/updates/blog/dynamic-story/2025/07/identifying-forest-invasive-species-in-fiji-and-tonga-using
  source: Pacific Community (SPC)
  published: 07 July, 2025
  banner: https://spc-cps.shorthandstories.com/depacific-invasive-species/assets/6YYMy0WBwE/original1-2048x1365.jpg

- title: Fiji maps its path to climate resilience through a GIS capacity-building workshop
  description: 24 government representatives from Fiji have successfully completed a week-long training on geospatial mapping and carbon stock assessment, marking a significant step forward in the country’s efforts to protect its blue carbon ecosystems and strengthen climate resilience.
  url: https://spc.int/updates/news/joint-release/2025/06/fiji-maps-its-path-to-climate-resilience-through-a-gis-capacity
  source: Pacific Community (SPC)
  published: 25 June, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-06/RS19883_Macblue%20Workshop-37.jpg.webp?itok=XuQD6q4E

- title: How SPC’s Digital Earth Pacific harnesses Artificial Intelligence to revolutionise our understanding of the environment
  description: Pacific Community’s (SPC) Digital Earth Pacific (DE Pacific) - an ambitious initiative that is revolutionising how Pacific countries and territories understand and respond to their environment using cutting-edge Artificial Intelligence (AI), Earth Observation (EO) data and very large-scale computing resources.  
  url: https://www.spc.int/updates/blog/dynamic-story/2025/05/how-spcs-digital-earth-pacific-harnesses-artificial-intelligence
  source: Pacific Community (SPC)
  published: 15 May, 2025
  banner: https://spc-cps.shorthandstories.com/how-spcs-digital-earth-pacific-harnesses-artificial-intelligence-to-revolutionise-our-understanding-of-the-environment/assets/tv8MKYos4b/map-25-1395x766.png

- title: GIS and remote sensing mapping to strengthen coastal conservation efforts in Solomon Islands
  description: A week-long training on using open-source GIS tools and remote sensing satellite data from SPC's Digital Earth Pacific (DE Pacific) will now enable Solomon Islands government officials and researchers to better map, monitor and protect seagrass and mangrove ecosystems.
  url: https://spc.int/updates/news/joint-release/2025/05/gis-and-remote-sensing-mapping-to-strengthen-coastal
  source: Pacific Community (SPC)
  published: 5 May, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-05/Group%20Pic.JPG.webp?itok=7gjutGHq

- title: "Beneath the surface: How seagrass, mangroves, science, and collaboration are reshaping climate resilience in Papua New Guinea"
  description: On the shorelines of Papua New Guinea, where coastal communities depend on the sea as both protector and provider, something vital lies hidden just beneath the surface, seagrass and mangrove ecosystems.
  url: https://www.spc.int/updates/blog/dynamic-story/2025/04/beneath-the-surface-how-seagrass-mangroves-science-and
  source: Pacific Community (SPC)
  published: 28 March, 2025
  banner: https://spc-cps.shorthandstories.com/macblue-de-pacific/assets/DVdLTtbUOU/png-dep-group-ohto-1080x720.jpg

- title: The Pacific Community (SPC) holds climate-related GIS capacity-building for PNG representatives
  description: 32 representatives from Papua New Guinea graduated today from a week-long course on geospatial analysis of seagrass and mangrove ecosystems.
  url: https://www.spc.int/updates/news/joint-release/2025/03/the-pacific-community-spc-holds-climate-related-gis-capacity
  source: Pacific Community (SPC)
  published: 20 March, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-03/PNG%20DEP%20group%20ohto.jpg.webp

- title: Cook Islands enhancing ecosystem monitoring capabilities
  description: Cook Islands will be able to enhance its ecosystem monitoring capabilities through the Pacific Community’s efforts to develop a land cover model for the country. The workshop is part of the Digital Earth Pacific land cover assessment skills transfer course for the Cook Islands.
  url: https://www.cookislandsnews.com/internal/national/environment/cook-islands-enhancing-ecosystem-monitoring-capabilities/#:~:text=Cook%20Islands%20will%20be%20able,cover%20model%20for%20the%20country.
  source: Cook Island News
  published: 19 September, 2024
  banner: https://www.cookislandsnews.com/wp-content/uploads/2024/09/24091811-scaled.jpg

- title: Making digital maps of Majuro
  description: Marshal Islands will be able to conduct land and marine areas mapping efectively through utilization of morden mapping technologies, boosting their capacity and enabling the participants to develop national land cover model for their country. The workshop was part of the Digital Earth Pacific land cover assessment skills transfer course for the Marshall Islands.
  url: https://www.spc.int/sites/default/files/2024-09/Journal%208-30-2024%20SPC%20digital%20earth%20Pacific%20training_page-0001.jpg
  source: Pacific Community (SPC)
  published: 08 September, 2024
  banner: https://pbs.twimg.com/media/GVdruZNWoAETtnK?format=jpg&name=large

  
- title: Cook Islands to benefit from new climate data project
  description: Cook Islands will be one of the major beneficiaries of a new project, called Digital Earth Pacific, being developed to capture extensive satellite information about climate change and natural disasters in the region.
  url: https://www.cookislandsnews.com/internal/national/weather/cook-islands-to-benefit-from-new-climate-data-project/
  source: Cook Island News
  published: 26 April, 2024
  banner: https://www.cookislandsnews.com/wp-content/uploads/2024/04/24042404.jpg


- title: The launch of Digital Earth Pacific during the 53rd CRGA and the 13th Conference
  description: The Pacific Community (SPC) launched Digital Earth Pacific as part of its 53rd meeting of the Committee of Representatives of Governments and Administrations and 13th Conference in Noumea, New Caledonia. The launch was officiated by Vice-President of the Federated States of Micronesia, Honourable Aren B Palik, who expressed how critical tools like this will be for the FSM. Digital Earth Pacific will now continue to evolve, providing more tools for countries to make informed decisions, such as tracking blue carbon or tracking illegal fishing in the Pacific in real time.
  url: https://www.spc.int/updates/news/media-release/2023/10/the-launch-of-digital-earth-pacific-during-the-53rd-meeting-of
  source: Pacific Community (SPC)
  published: October, 2023
  banner: https://www.spc.int/sites/default/files/images/GEM/DSCF0868.JPG

- title: Digital Earth Pacific - how open data is combatting rising tides?
  description: Globally, the effects of climate change are already being observed through increases in drought, forest fires, sea level rise, flooding, and hunger. Given the vulnerability of Pacific Island countries and territories (PICTs) in this respect, the Pacific region specifically faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods, and ensuring sustainable food systems.  Digital public infrastructure (DPI) that supports the flow and exchange of data and services is critical in overcoming these challenges.
  url: https://dial.global/digital-earth-pacific-how-open-data-is-combatting-rising-tides/
  source: Aditya Agrawal, Digital Impact Alliance
  published: September, 2023
  banner: https://dial.global/wp-content/uploads/2023/09/AdobeStock_556113380-1060x706.jpeg

- title: SPC hosts first DEP LCAST national workshop in Nuku’alofa
  description: A week-long workshop on Digital Earth Pacific (DEP) – Tongatapu remote sensing Land Cover Assessment Skills Transfer (LCAST) is currently underway at Tanoa International Dateline Hotel, aimed to address the specific outcomes highlighted in the Needs Assessment Report by Tonga government officials in August, 2021.
  url: https://www.gov.to/press-release/spc-hosts-first-dep-lcast-national-workshop-in-nukualofa/
  source: Government of Tonga
  published: July, 2023
  banner: https://deppcpublicstorage.blob.core.windows.net/output/website/to_group.jpg

- title: Tongan land use monitored through satellite imagery data
  description: Monitoring of land use through Earth observations and satellite imagery data, will help governments in the Pacific Islands better manage their limited resources. Now the Pacific Community (SPC) is supporting the development of the technical skills needed by governments to collect data from remote sensing and to interpret it.
  url: https://matangitonga.to/2023/07/24/tongan-land-use-monitored-through-satellite-imagery-data
  source: Matangi Tonga
  published: April, 2023
  banner: https://matangitonga.to/sites/default/files/20230724_DEP_LCAST_TVJ7855_955x500px.jpg

- title: Project to unlock 'exponential opportunity' for Pacific
  description: The Pacific Community's Digital Earth Pacific project will unlock exponential opportunity in the region, the regional body's chief says.
  url: https://www.rnz.co.nz/international/pacific-news/467282/project-to-unlock-exponential-opportunity-for-pacific
  source: Radio New Zealand (RNZ)
  published: May, 2022
  banner: https://rnz-ressh.cloudinary.com/image/upload/s--EPVmWcKK--/ar_16:10,c_fill,f_auto,g_auto,q_auto,w_1050/v1644476939/4M6EZ1I_copyright_image_271073

- title: Vulnerable Pacific Islands look to data to cope with disasters and help heal the environment
  description: Mention the tropical islands of the Pacific and thoughts of soft sand, blue lagoons and swaying palm trees come readily to mind. But there is an ominous flip side to this picture-postcard image. These are among the world’s most vulnerable places for natural disasters and the impact of climate change.
  url: https://www.spc.int/updates/blog/partners/2022/03/vulnerable-pacific-islands-look-to-data-to-cope-with-disasters-and
  source: Pacific Community (SPC)
  published: march 2022
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2022-03/Cover.JPG?itok=2LsWPLzz

- title: Satellite technology and digital tools help quantify climate change impact and drive solutions to the world’s greatest challenges
  description: A learning event with more than 85 participants from across Pacific countries and territories engaged with global leaders in the use of satellite data to inform and improve how we protect our planet into the future.
  url: https://www.spc.int/updates/blog/2021/10/satellite-technology-and-digital-tools-help-quantify-climate-change-impact-and
  source: Pacific Community (SPC)
  published: October, 2021
  banner: https://www.spc.int/sites/default/files/documents/FB%20Group%20Photo%20Digital%20Earth%20Pacific%20Speaker%20.jpg

- title: Global satellites to boost access to relevant data in the Pacific
  description: Pacific Countries are committed to the development of a new Digital Earth Pacific Program that will allow the use of global satellite systems to better understand the changes to our environment and countries in the Pacific.
  url: https://www.spc.int/updates/blog/2021/05/global-satellites-to-boost-access-to-relevant-data-in-the-pacific
  source: Pacific Community (SPC)
  published: May, 2021
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2021-05/1024px-Iss007e10807.jpg?itok=874cV4pF

- title: Better data will lead to better decisions for our blue continent
  description: Understanding how our planet is changing over time and what impact this has on our people, communities and countries is paramount for making informed decisions.  This includes understanding critical issues such as how our coastlines are changing and what this means.
  url: https://www.spc.int/updates/blog/2019/11/better-data-will-lead-to-better-decisions-for-our-blue-continent
  source: Pacific Community (SPC)
  published: November, 2019
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2019-11/GEOWeek%20Earth%20Obs%20Announcement%202019%20whole%20team.jpg

- title: Digital Earth Pacific - A Demand-Driven Approach to Addressing National Development Priorities through Earth Observations
  description: The Pacific region faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods and ensuring sustainable food systems.
  url: https://www.geospatialworld.net/prime/special-features/digital-earth-pacific-a-demand-driven-approach-to-addressing-national-development-priorities-through-earth-observations/
  source: Geospatial World
  published: 2021
  banner: https://www.geospatialworld.net/wp-content/uploads/2022/05/Digital-Earth-Pacific-Figure-1.png
