- title: Digital Earth Pacific - how open data is combatting rising tides?
  description: Globally, the effects of climate change are already being observed through increases in drought, forest fires, sea level rise, flooding, and hunger. Given the vulnerability of Pacific Island countries and territories (PICTs) in this respect, the Pacific region specifically faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods, and ensuring sustainable food systems.  Digital public infrastructure (DPI) that supports the flow and exchange of data and services is critical in overcoming these challenges.
  url: https://dial.global/digital-earth-pacific-how-open-data-is-combatting-rising-tides/
  source: Aditya Agrawal, Digital Impact Alliance
  published: September, 2023
  banner: https://dial.global/wp-content/uploads/2023/09/AdobeStock_556113380-1060x706.jpeg

- title: SPC hosts first DEP LCAST national workshop in Nuku’alofa
  description: A week-long workshop on Digital Earth Pacific (DEP) – Tongatapu remote sensing Land Cover Assessment Skills Transfer (LCAST) is currently underway at Tanoa International Dateline Hotel, aimed to address the specific outcomes highlighted in the Needs Assessment Report by Tonga government officials in August, 2021.
  url: https://www.gov.to/press-release/spc-hosts-first-dep-lcast-national-workshop-in-nukualofa/
  source: Government of Tonga
  published: July, 2023
  banner: https://www.gov.to/wp-content/uploads/2023/07/DSC_3849-21-825x391.jpg

- title: Tongan land use monitored through satellite imagery data
  description: Monitoring of land use through Earth observations and satellite imagery data, will help governments in the Pacific Islands better manage their limited resources. Now the Pacific Community (SPC) is supporting the development of the technical skills needed by governments to collect data from remote sensing and to interpret it.
  url: https://matangitonga.to/2023/07/24/tongan-land-use-monitored-through-satellite-imagery-data
  source: Matangi Tonga
  published: April, 2023
  banner: https://matangitonga.to/sites/default/files/20230724_DEP_LCAST_TVJ7855_955x500px.jpg

- title: Project to unlock 'exponential opportunity' for Pacific
  description: The Pacific Community's Digital Earth Pacific project will unlock exponential opportunity in the region, the regional body's chief says.
  url: https://www.rnz.co.nz/international/pacific-news/467282/project-to-unlock-exponential-opportunity-for-pacific
  source: Radio New Zealand (RNZ)
  published: May, 2022
  banner: https://rnz-ressh.cloudinary.com/image/upload/s--EPVmWcKK--/ar_16:10,c_fill,f_auto,g_auto,q_auto,w_1050/v1644476939/4M6EZ1I_copyright_image_271073

- title: Vulnerable Pacific Islands look to data to cope with disasters and help heal the environment
  description: Mention the tropical islands of the Pacific and thoughts of soft sand, blue lagoons and swaying palm trees come readily to mind. But there is an ominous flip side to this picture-postcard image. These are among the world’s most vulnerable places for natural disasters and the impact of climate change.
  url: https://www.spc.int/updates/blog/partners/2022/03/vulnerable-pacific-islands-look-to-data-to-cope-with-disasters-and
  source: Pacific Community (SPC)
  published: march 2022
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2022-03/Cover.JPG?itok=2LsWPLzz

- title: Satellite technology and digital tools help quantify climate change impact and drive solutions to the world’s greatest challenges
  description: A learning event with more than 85 participants from across Pacific countries and territories engaged with global leaders in the use of satellite data to inform and improve how we protect our planet into the future.
  url: https://www.spc.int/updates/blog/2021/10/satellite-technology-and-digital-tools-help-quantify-climate-change-impact-and
  source: Pacific Community (SPC)
  published: October, 2021
  banner: https://www.spc.int/sites/default/files/documents/FB%20Group%20Photo%20Digital%20Earth%20Pacific%20Speaker%20.jpg

- title: Global satellites to boost access to relevant data in the Pacific
  description: Pacific Countries are committed to the development of a new Digital Earth Pacific Program that will allow the use of global satellite systems to better understand the changes to our environment and countries in the Pacific.
  url: https://www.spc.int/updates/blog/2021/05/global-satellites-to-boost-access-to-relevant-data-in-the-pacific
  source: Pacific Community (SPC)
  published: May, 2021
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2021-05/1024px-Iss007e10807.jpg?itok=874cV4pF

- title: Better data will lead to better decisions for our blue continent
  description: Understanding how our planet is changing over time and what impact this has on our people, communities and countries is paramount for making informed decisions.  This includes understanding critical issues such as how our coastlines are changing and what this means.
  url: https://www.spc.int/updates/blog/2019/11/better-data-will-lead-to-better-decisions-for-our-blue-continent
  source: Pacific Community (SPC)
  published: November, 2019
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2019-11/GEOWeek%20Earth%20Obs%20Announcement%202019%20whole%20team.jpg

- title: Digital Earth Pacific - A Demand-Driven Approach to Addressing National Development Priorities through Earth Observations
  description: The Pacific region faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods and ensuring sustainable food systems.
  url: https://www.geospatialworld.net/prime/special-features/digital-earth-pacific-a-demand-driven-approach-to-addressing-national-development-priorities-through-earth-observations/
  source: Geospatial World
  published: 2021
  banner: https://www.geospatialworld.net/wp-content/uploads/2022/05/Digital-Earth-Pacific-Figure-1.png
