- title: Fiji maps its path to climate resilience through a GIS capacity-building workshop
  description: 24 government representatives from Fiji have successfully completed a week-long training on geospatial mapping and carbon stock assessment, marking a significant step forward in the country’s efforts to protect its blue carbon ecosystems and strengthen climate resilience.
  source: Pacific Community (SPC)
  published: 25 June, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-06/RS19883_Macblue%20Workshop-37.jpg.webp?itok=XuQD6q4E

- title: How SPC’s Digital Earth Pacific harnesses Artificial Intelligence to revolutionise our understanding of the environment
  description: Pacific Community’s (SPC) Digital Earth Pacific (DE Pacific) - an ambitious initiative that is revolutionising how Pacific countries and territories understand and respond to their environment using cutting-edge Artificial Intelligence (AI), Earth Observation (EO) data and very large-scale computing resources.  
  source: Pacific Community (SPC)
  published: 15 May, 2025
  banner: https://spc-cps.shorthandstories.com/how-spcs-digital-earth-pacific-harnesses-artificial-intelligence-to-revolutionise-our-understanding-of-the-environment/assets/tv8MKYos4b/map-25-1395x766.png

- title: GIS and remote sensing mapping to strengthen coastal conservation efforts in Solomon Islands
  description: A week-long training on using open-source GIS tools and remote sensing satellite data from SPC's Digital Earth Pacific (DE Pacific) will now enable Solomon Islands government officials and researchers to better map, monitor and protect seagrass and mangrove ecosystems.
  source: Pacific Community (SPC)
  published: 5 May, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-05/Group%20Pic.JPG.webp?itok=7gjutGHq

- title: Beneath the surface: How seagrass, mangroves, science, and collaboration are reshaping climate resilience in Papua New Guinea
  description: On the shorelines of Papua New Guinea, where coastal communities depend on the sea as both protector and provider, something vital lies hidden just beneath the surface: seagrass and mangrove ecosystems.
  source: Pacific Community (SPC)
  published: 28 March, 2025
  banner: https://spc-cps.shorthandstories.com/macblue-de-pacific/assets/DVdLTtbUOU/png-dep-group-ohto-1080x720.jpg

- title: The Pacific Community (SPC) holds climate-related GIS capacity-building for PNG representatives
  description: 32 representatives from Papua New Guinea graduated today from a week-long course on geospatial analysis of seagrass and mangrove ecosystems.
  source: Pacific Community (SPC)
  published: 20 March, 2025
  banner: https://spc.int/sites/default/files/styles/max_1300x1300/public/2025-03/PNG%20DEP%20group%20ohto.jpg.webp

- title: Cook Islands enhancing ecosystem monitoring capabilities
  description: Cook Islands will be able to enhance its ecosystem monitoring capabilities through the Pacific Community’s efforts to develop a land cover model for the country. The workshop is part of the Digital Earth Pacific land cover assessment skills transfer course for the Cook Islands.
  url: https://www.cookislandsnews.com/internal/national/environment/cook-islands-enhancing-ecosystem-monitoring-capabilities/#:~:text=Cook%20Islands%20will%20be%20able,cover%20model%20for%20the%20country.
  source: Cook Island News
  published: 19 September, 2024
  banner: https://www.cookislandsnews.com/wp-content/uploads/2024/09/24091811-scaled.jpg

- title: Making digital maps of Majuro
  description: Marshal Islands will be able to conduct land and marine areas mapping efectively through utilization of morden mapping technologies, boosting their capacity and enabling the participants to develop national land cover model for their country. The workshop was part of the Digital Earth Pacific land cover assessment skills transfer course for the Marshall Islands.
  url: https://www.spc.int/sites/default/files/2024-09/Journal%208-30-2024%20SPC%20digital%20earth%20Pacific%20training_page-0001.jpg
  source: Pacific Community (SPC)
  published: 08 September, 2024
  banner: https://pbs.twimg.com/media/GVdruZNWoAETtnK?format=jpg&name=large

  
- title: Cook Islands to benefit from new climate data project
  description: Cook Islands will be one of the major beneficiaries of a new project, called Digital Earth Pacific, being developed to capture extensive satellite information about climate change and natural disasters in the region.
  url: https://www.cookislandsnews.com/internal/national/weather/cook-islands-to-benefit-from-new-climate-data-project/
  source: Cook Island News
  published: 26 April, 2024
  banner: https://www.cookislandsnews.com/wp-content/uploads/2024/04/24042404.jpg


- title: The launch of Digital Earth Pacific during the 53rd CRGA and the 13th Conference
  description: The Pacific Community (SPC) launched Digital Earth Pacific as part of its 53rd meeting of the Committee of Representatives of Governments and Administrations and 13th Conference in Noumea, New Caledonia. The launch was officiated by Vice-President of the Federated States of Micronesia, Honourable Aren B Palik, who expressed how critical tools like this will be for the FSM. Digital Earth Pacific will now continue to evolve, providing more tools for countries to make informed decisions, such as tracking blue carbon or tracking illegal fishing in the Pacific in real time.
  url: https://www.spc.int/updates/news/media-release/2023/10/the-launch-of-digital-earth-pacific-during-the-53rd-meeting-of
  source: Pacific Community (SPC)
  published: October, 2023
  banner: https://www.spc.int/sites/default/files/images/GEM/DSCF0868.JPG

- title: Digital Earth Pacific - how open data is combatting rising tides?
  description: Globally, the effects of climate change are already being observed through increases in drought, forest fires, sea level rise, flooding, and hunger. Given the vulnerability of Pacific Island countries and territories (PICTs) in this respect, the Pacific region specifically faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods, and ensuring sustainable food systems.  Digital public infrastructure (DPI) that supports the flow and exchange of data and services is critical in overcoming these challenges.
  url: https://dial.global/digital-earth-pacific-how-open-data-is-combatting-rising-tides/
  source: Aditya Agrawal, Digital Impact Alliance
  published: September, 2023
  banner: https://dial.global/wp-content/uploads/2023/09/AdobeStock_556113380-1060x706.jpeg

- title: SPC hosts first DEP LCAST national workshop in Nuku’alofa
  description: A week-long workshop on Digital Earth Pacific (DEP) – Tongatapu remote sensing Land Cover Assessment Skills Transfer (LCAST) is currently underway at Tanoa International Dateline Hotel, aimed to address the specific outcomes highlighted in the Needs Assessment Report by Tonga government officials in August, 2021.
  url: https://www.gov.to/press-release/spc-hosts-first-dep-lcast-national-workshop-in-nukualofa/
  source: Government of Tonga
  published: July, 2023
  banner: https://deppcpublicstorage.blob.core.windows.net/output/website/to_group.jpg

- title: Tongan land use monitored through satellite imagery data
  description: Monitoring of land use through Earth observations and satellite imagery data, will help governments in the Pacific Islands better manage their limited resources. Now the Pacific Community (SPC) is supporting the development of the technical skills needed by governments to collect data from remote sensing and to interpret it.
  url: https://matangitonga.to/2023/07/24/tongan-land-use-monitored-through-satellite-imagery-data
  source: Matangi Tonga
  published: April, 2023
  banner: https://matangitonga.to/sites/default/files/20230724_DEP_LCAST_TVJ7855_955x500px.jpg

- title: Project to unlock 'exponential opportunity' for Pacific
  description: The Pacific Community's Digital Earth Pacific project will unlock exponential opportunity in the region, the regional body's chief says.
  url: https://www.rnz.co.nz/international/pacific-news/467282/project-to-unlock-exponential-opportunity-for-pacific
  source: Radio New Zealand (RNZ)
  published: May, 2022
  banner: https://rnz-ressh.cloudinary.com/image/upload/s--EPVmWcKK--/ar_16:10,c_fill,f_auto,g_auto,q_auto,w_1050/v1644476939/4M6EZ1I_copyright_image_271073

- title: Vulnerable Pacific Islands look to data to cope with disasters and help heal the environment
  description: Mention the tropical islands of the Pacific and thoughts of soft sand, blue lagoons and swaying palm trees come readily to mind. But there is an ominous flip side to this picture-postcard image. These are among the world’s most vulnerable places for natural disasters and the impact of climate change.
  url: https://www.spc.int/updates/blog/partners/2022/03/vulnerable-pacific-islands-look-to-data-to-cope-with-disasters-and
  source: Pacific Community (SPC)
  published: march 2022
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2022-03/Cover.JPG?itok=2LsWPLzz

- title: Satellite technology and digital tools help quantify climate change impact and drive solutions to the world’s greatest challenges
  description: A learning event with more than 85 participants from across Pacific countries and territories engaged with global leaders in the use of satellite data to inform and improve how we protect our planet into the future.
  url: https://www.spc.int/updates/blog/2021/10/satellite-technology-and-digital-tools-help-quantify-climate-change-impact-and
  source: Pacific Community (SPC)
  published: October, 2021
  banner: https://www.spc.int/sites/default/files/documents/FB%20Group%20Photo%20Digital%20Earth%20Pacific%20Speaker%20.jpg

- title: Global satellites to boost access to relevant data in the Pacific
  description: Pacific Countries are committed to the development of a new Digital Earth Pacific Program that will allow the use of global satellite systems to better understand the changes to our environment and countries in the Pacific.
  url: https://www.spc.int/updates/blog/2021/05/global-satellites-to-boost-access-to-relevant-data-in-the-pacific
  source: Pacific Community (SPC)
  published: May, 2021
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2021-05/1024px-Iss007e10807.jpg?itok=874cV4pF

- title: Better data will lead to better decisions for our blue continent
  description: Understanding how our planet is changing over time and what impact this has on our people, communities and countries is paramount for making informed decisions.  This includes understanding critical issues such as how our coastlines are changing and what this means.
  url: https://www.spc.int/updates/blog/2019/11/better-data-will-lead-to-better-decisions-for-our-blue-continent
  source: Pacific Community (SPC)
  published: November, 2019
  banner: https://www.spc.int/sites/default/files/styles/featured_image/public/featuredimages/blog/2019-11/GEOWeek%20Earth%20Obs%20Announcement%202019%20whole%20team.jpg

- title: Digital Earth Pacific - A Demand-Driven Approach to Addressing National Development Priorities through Earth Observations
  description: The Pacific region faces unique challenges in managing natural resources and biodiversity, securing economies and livelihoods and ensuring sustainable food systems.
  url: https://www.geospatialworld.net/prime/special-features/digital-earth-pacific-a-demand-driven-approach-to-addressing-national-development-priorities-through-earth-observations/
  source: Geospatial World
  published: 2021
  banner: https://www.geospatialworld.net/wp-content/uploads/2022/05/Digital-Earth-Pacific-Figure-1.png
