name: Build and Push to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: write
    env:
      REACT_APP_API_ROOT: ${{ secrets.API_ROOT }}
      REACT_APP_IMAGE_API_ROOT: ${{ secrets.IMAGE_API_ROOT }}
      REACT_APP_ONEDS_TENANT_KEY: ${{ secrets.ONEDS_TENANT_KEY }}
      REACT_APP_AZMAPS_KEY: ${{ secrets.AZMAPS_KEY }}
      REACT_APP_HUB_URL: ${{ secrets.HUB_URL }}
      REACT_APP_AUTH_URL: ${{ secrets.AUTH_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Build docs and metadata
        run: ./scripts/update
      - name: Test and lint
        run: ./scripts/test
      - name: Inject disallow crawling for robots.txt
        run: |
          echo -e "User-agent: *\nDisallow: /\n" > public/robots.txt
      - name: Build optimized bundle
        id: build-bundle
        run: ./scripts/cibuild
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
